sudo: false

language: python

python:
- "2.7"
- "3.4"
- "3.8"

env:
- SQLA_VERSION=1.0
- SQLA_VERSION=1.1
- SQLA_VERSION=1.2
- SQLA_VERSION=1.3

install:
- pip install tox-travis
- pip install codecov

script:
- tox

after_success:
- codecov
